# -*- coding: utf-8 -*-
"""
GyroBalance Cloud Backend - app.py (RENDER VERSION)
Fixes: Keras loading, 404 Route errors, and Professional PDF generation.
"""

import os
import json
import uuid
import joblib
import numpy as np
import threading
from datetime import datetime
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS

# AI & Physics Imports
import tensorflow as tf
from tensorflow.keras import models
import trimesh
from fpdf import FPDF

# ─────────────────────────────────────────────
# APP SETUP & CONFIG
# ─────────────────────────────────────────────
app = Flask(__name__)
CORS(app)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CUSTOM_DIR = os.path.join(BASE_DIR, "custom_blades")
MODELS_DIR = os.path.join(BASE_DIR, "models")
STATIC_DIR = os.path.join(BASE_DIR, "static")

# Ensure critical directories exist
for folder in [CUSTOM_DIR, MODELS_DIR, STATIC_DIR]:
    os.makedirs(folder, exist_ok=True)

SENSOR_POS = [9.0, 26.0, 42.0]
BALANCE_TOLERANCE = 0.15

# ─────────────────────────────────────────────
# CORE AI LOADER (SAFE VERSION)
# ─────────────────────────────────────────────
model_cache = {}

def get_model_and_meta(blade_id):
    """Retrieves AI model and metadata. Uses compile=False to fix Render version errors."""
    blade_id = str(blade_id)
    if blade_id in model_cache:
        return model_cache[blade_id]

    try:
        if blade_id in ["0", "1"]:
            # Original Master Model
            model_path = os.path.join(MODELS_DIR, "gyro_master_model.keras")
            meta_path = os.path.join(MODELS_DIR, "blade_meta.pkl")
            meta_data = joblib.load(meta_path)
            meta = meta_data['B1'] if blade_id == "0" else meta_data['B2']
        else:
            # Custom Blade Isolated Path
            path = os.path.join(CUSTOM_DIR, blade_id)
            model_path = os.path.join(path, "model.keras")
            meta_path = os.path.join(path, "meta.pkl")
            meta = list(joblib.load(meta_path).values())[0]

        # FIX: compile=False ignores quantization_config errors in Render's TF version
        model = tf.keras.models.load_model(model_path, compile=False)
        model_cache[blade_id] = (model, meta)
        return model, meta
    except Exception as e:
        print(f"❌ Critical Model Load Error for {blade_id}: {e}")
        return None, None

# ─────────────────────────────────────────────
# PROFESSIONAL PDF REPORT GENERATOR
# ─────────────────────────────────────────────
class ProfessionalReport(FPDF):
    def header(self):
        # App Header with Logo
        logo_path = os.path.join(STATIC_DIR, "logo.png")
        if os.path.exists(logo_path):
            self.image(logo_path, 10, 8, 30)
        
        self.set_font('Arial', 'B', 16)
        self.set_text_color(63, 81, 181) # Indigo
        self.cell(80)
        self.cell(30, 10, 'GYROBALANCE AI SYSTEM', 0, 1, 'C')
        
        self.set_font('Arial', 'B', 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, 'INDUSTRIAL GRADE BLADE CALIBRATION & DIAGNOSTICS', 0, 1, 'C')
        self.ln(10)
        self.set_draw_color(63, 81, 181)
        self.line(10, 35, 200, 35)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by GyroBalance Cloud AI | SREC Engineering Labs | Page {self.page_no()}', 0, 0, 'C')

    def bold_heading(self, text):
        self.set_font('Arial', 'B', 11)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 10, f"  {text.upper()}", 0, 1, 'L', True)
        self.ln(2)

    def data_line(self, label, value):
        self.set_font('Arial', 'B', 10)
        self.cell(60, 8, f"{label}:", 0, 0)
        self.set_font('Arial', '', 10)
        self.cell(0, 8, str(value), 0, 1)

# ─────────────────────────────────────────────
# API ROUTES
# ─────────────────────────────────────────────

@app.route('/')
def home():
    return jsonify({"status": "GyroBalance Cloud AI is LIVE", "version": "2.0.1"})

@app.route('/analyze', methods=['POST'])
def analyze():
    data = request.json
    if not data or data.get('ping'): 
        return jsonify({"status": "online"})

    blade_id = str(data.get('blade_id', "0"))
    w_root = float(data.get('w_root', 0))
    w_mid = float(data.get('w_mid', 0))
    w_tip = float(data.get('w_tip', 0))

    model, meta = get_model_and_meta(blade_id)
    if not model:
        return jsonify({"error": "AI Neural Engine failed to initialize."}), 500

    target_cg, target_mass = meta
    total_g = max(1e-9, w_root + w_mid + w_tip)
    
    # Run AI Inference
    # Model expects [type, w1, w2, w3] in kg
    input_data = np.array([[float(blade_id) if blade_id.isdigit() else 2.0, w_root/1000, w_mid/1000, w_tip/1000]])
    preds = model.predict(input_data)
    
    # Extract Predicted CG and Diagnosis
    pred_cg = float(preds[0][0][0])
    defect_probs = preds[1][0]
    defect_idx = np.argmax(defect_probs)

    defect_map = {
        0: ("HEALTHY DNA", "Validated structural load parity.", "DNA CONFIRMED."),
        1: ("RESIN POOL", "Localized excess density at tip.", "ANOMALOUS TIP MASS."),
        2: ("AIR VOID", "Critical density dropout detected.", "STRUCTURAL BREACH."),
        3: ("INFILL ERROR", "Non-linear mass distribution drift.", "INFILL DRIFT.")
    }
    
    status, diag_desc, sig = defect_map[defect_idx]
    deviation = pred_cg - target_cg
    is_balanced = abs(deviation) < BALANCE_TOLERANCE

    # Resolution Logic
    if not is_balanced:
        action = "ADD WEIGHT"
        corr_loc = 0.0 if deviation > 0 else 45.0
        corr_mass = (total_g * abs(deviation)) / (abs(target_cg - corr_loc) + 1e-9)
    else:
        action, status, corr_mass, corr_loc = "NONE", "BALANCED", 0.0, 0.0

    result = {
        "w_root": w_root, "w_mid": w_mid, "w_tip": w_tip,
        "cg": round(pred_cg, 2), "target_cg": round(target_cg, 2),
        "deviation": round(deviation, 3), "status": status,
        "status_desc": sig, "diagnosis_details": diag_desc,
        "target_mass": target_mass,
        "correction": {"action": action, "mass": round(corr_mass, 1), "location": round(corr_loc, 1)},
        "report": {
            "items": [
                {"sensor": "Root Zone", "value": w_root/1000, "impact": f"{(w_root/total_g)*100:.1f}% Load"},
                {"sensor": "Mid Span", "value": w_mid/1000, "impact": f"{(w_mid/total_g)*100:.1f}% Load"},
                {"sensor": "Tip Zone", "value": w_tip/1000, "impact": f"{(w_tip/total_g)*100:.1f}% Load"}
            ],
            "interpretation": f"AI Diagnostic: {status}."
        }
    }
    return jsonify(result)

@app.route('/list-blades', methods=['GET'])
def list_blades():
    """Returns all custom blades registered in the isolated storage"""
    blades = []
    if os.path.exists(CUSTOM_DIR):
        for b_id in os.listdir(CUSTOM_DIR):
            meta_file = os.path.join(CUSTOM_DIR, b_id, "meta.pkl")
            if os.path.exists(meta_file):
                blades.append({"id": b_id, "name": f"Custom Blade {b_id}"})
    return jsonify(blades)

@app.route('/get-stl/<blade_id>', methods=['GET'])
def get_stl(blade_id):
    """Serves the STL file for the 3D visualizer"""
    path = os.path.join(CUSTOM_DIR, blade_id, "blade.stl")
    if os.path.exists(path):
        return send_file(path)
    return jsonify({"error": "STL not found"}), 404

@app.route('/add-blade', methods=['POST'])
def add_blade():
    """Saves STL and extracts DNA for a new blade profile"""
    if 'stl' not in request.files: return jsonify({"error": "No STL file"}), 400
    
    file = request.files['stl']
    blade_id = str(uuid.uuid4())[:8]
    folder = os.path.join(CUSTOM_DIR, blade_id)
    os.makedirs(folder, exist_ok=True)
    
    stl_path = os.path.join(folder, "blade.stl")
    file.save(stl_path)
    
    # Physics Extraction
    mesh = trimesh.load(stl_path)
    density = float(request.form.get('density', 1.25))
    scale = 0.1
    ideal_cg = float(mesh.centroid[0]) * scale
    ideal_mass = (float(mesh.volume) * (scale**3) * density) / 1000
    
    meta = {blade_id: [ideal_cg, ideal_mass]}
    joblib.dump(meta, os.path.join(folder, "meta.pkl"))

    # Copy master model as base (Isolated Training would happen here)
    master_path = os.path.join(MODELS_DIR, "gyro_master_model.keras")
    if os.path.exists(master_path):
        target_model_path = os.path.join(folder, "model.keras")
        models.load_model(master_path, compile=False).save(target_model_path)

    return jsonify({"status": "registered", "blade_id": blade_id, "cg": ideal_cg})

@app.route('/download-report', methods=['POST'])
def download_report():
    """Generates the professional PDF with all measured data"""
    data = request.json
    pdf = ProfessionalReport()
    pdf.add_page()
    
    pdf.bold_heading("1. Blade Profile Information")
    pdf.data_line("Timestamp", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    pdf.data_line("Design Target CG", f"{data.get('target_cg', 0)} cm")
    pdf.data_line("Design Target Mass", f"{data.get('target_mass', 0)*1000:.1f} g")
    
    pdf.ln(5)
    pdf.bold_heading("2. Raw Load Analytics (3 Points)")
    pdf.data_line("Root Zone Load (S1)", f"{data.get('w_root', 0)} g")
    pdf.data_line("Mid Span Load (S2)", f"{data.get('w_mid', 0)} g")
    pdf.data_line("Tip Zone Load (S3)", f"{data.get('w_tip', 0)} g")
    pdf.data_line("Total Measured Mass", f"{data.get('w_root',0)+data.get('w_mid',0)+data.get('w_tip',0):.1f} g")

    pdf.ln(5)
    pdf.bold_heading("3. AI Neural Diagnostic Result")
    pdf.data_line("Measured Center of Gravity", f"{data.get('cg', 0)} cm")
    pdf.data_line("Axial Drift / Deviation", f"{data.get('deviation', 0)} cm")
    pdf.data_line("Classification", data.get('status', 'Unknown'))
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 8, f"AI INTERPRETATION: {data.get('status_desc', '')} {data.get('diagnosis_details', '')}")
    
    pdf.ln(5)
    pdf.bold_heading("4. Engineering Mitigation Plan")
    correction = data.get('correction', {})
    if correction.get('action') != "NONE":
        pdf.set_text_color(200, 0, 0) # Red
        pdf.data_line("Required Action", correction.get('action'))
        pdf.data_line("Counterweight Mass", f"{correction.get('mass')} g")
        pdf.data_line("Placement Coordinate", f"{correction.get('location')} cm from Root")
    else:
        pdf.set_text_color(0, 150, 0) # Green
        pdf.cell(0, 10, "VALIDATED: No structural mitigation required.", 0, 1)

    pdf_path = os.path.join(BASE_DIR, "report.pdf")
    pdf.output(pdf_path)
    return send_file(pdf_path, as_attachment=True)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=int(os.environ.get("PORT", 5000)))
