# -*- coding: utf-8 -*-
"""
GyroBalance Professional Reporter - reporter.py
Generates industrial-grade PDF diagnostic reports for blade balancing.
"""

from fpdf import FPDF
import datetime
import os

class BladeReportGenerator(FPDF):
    def __init__(self, logo_path=None):
        super().__init__()
        self.logo_path = logo_path
        self.primary_color = (63, 81, 181)  # Indigo
        self.secondary_color = (243, 246, 248) # Light Gray background
        self.text_dark = (30, 41, 59)
        self.text_light = (100, 116, 139)

    def header(self):
        # Background Header Bar
        self.set_fill_color(255, 255, 255)
        self.rect(0, 0, 210, 40, 'F')
        
        # Logo
        if self.logo_path and os.path.exists(self.logo_path):
            self.image(self.logo_path, 10, 10, 25)
        
        # App Title & Details
        self.set_xy(40, 12)
        self.set_font('Arial', 'B', 16)
        self.set_text_color(*self.primary_color)
        self.cell(0, 10, 'GYROBALANCE AI SYSTEM', 0, 1, 'L')
        
        self.set_x(40)
        self.set_font('Arial', 'B', 8)
        self.set_text_color(*self.text_light)
        self.cell(0, 5, 'INDUSTRIAL GRADE BLADE KINEMATICS & LOAD ANALYTICS', 0, 1, 'L')
        
        # Line Decorator
        self.set_draw_color(*self.primary_color)
        self.set_line_width(0.5)
        self.line(10, 38, 200, 38)
        self.ln(10)

    def footer(self):
        self.set_y(-20)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.set_draw_color(230, 230, 230)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(0, 10, f'Report Generated by GyroBalance Cloud AI on {date_str} | SREC Engineering Labs', 0, 0, 'C')

    def create_section_header(self, title):
        self.ln(5)
        self.set_font('Arial', 'B', 11)
        self.set_text_color(*self.primary_color)
        self.set_fill_color(*self.secondary_color)
        self.cell(0, 10, f"  {title.upper()}", 0, 1, 'L', True)
        self.ln(3)

    def add_info_row(self, label, value, unit="", bold_val=False):
        self.set_font('Arial', 'B', 9)
        self.set_text_color(*self.text_light)
        self.cell(50, 8, f"{label}:", 0, 0)
        
        self.set_font('Arial', 'B' if bold_val else '', 10)
        self.set_text_color(*self.text_dark)
        self.cell(0, 8, f"{value} {unit}", 0, 1)

    def generate(self, data, output_path):
        self.add_page()
        
        # 1. BLADE PROFILE DATA
        self.create_section_header("1. Profile Specification")
        self.add_info_row("Blade Identifier", data.get('blade_id', 'Unknown'))
        self.add_info_row("Design Target CG", f"{data.get('target_cg', 0):.2f}", "cm Axial")
        self.add_info_row("Design Target Mass", f"{data.get('target_mass', 0)*1000:.1f}", "grams")
        
        # 2. RAW SENSOR DATA
        self.create_section_header("2. Sensor Load Distribution")
        col_width = 60
        self.set_font('Arial', 'B', 9)
        self.set_fill_color(250, 250, 250)
        self.cell(col_width, 10, "  Zone", 1, 0, 'L', True)
        self.cell(col_width, 10, "  Measured Load", 1, 0, 'L', True)
        self.cell(col_width, 10, "  Impact Ratio", 1, 1, 'L', True)
        
        self.set_font('Arial', '', 9)
        total_w = data['w_root'] + data['w_mid'] + data['w_tip']
        zones = [
            ("Root Zone (S1)", data['w_root']),
            ("Mid Span (S2)", data['w_mid']),
            ("Tip Zone (S3)", data['w_tip'])
        ]
        for name, val in zones:
            impact = (val / total_w * 100) if total_w > 0 else 0
            self.cell(col_width, 10, f"  {name}", 1)
            self.cell(col_width, 10, f"  {val:.1f} g", 1)
            self.cell(col_width, 10, f"  {impact:.1f} %", 1, 1)

        # 3. AI DIAGNOSTIC SUMMARY
        self.create_section_header("3. Neural AI Diagnostic Result")
        self.add_info_row("Calculated Center of Gravity", f"{data.get('cg', 0):.2f}", "cm", True)
        self.add_info_row("Drift / Deviation", f"{data.get('deviation', 0):.3f}", "cm", True)
        
        # Status Box
        status = data.get('status', 'N/A')
        status_color = (22, 163, 74) if status == "BALANCED" or "HEALTHY" in status else (220, 38, 38)
        self.ln(2)
        self.set_font('Arial', 'B', 10)
        self.set_text_color(*status_color)
        self.cell(0, 10, f"CLASSIFICATION: {status}", 0, 1)
        
        self.set_text_color(*self.text_dark)
        self.set_font('Arial', 'I', 9)
        self.multi_cell(0, 6, f"AI Logic Trace: {data.get('status_desc', 'No signature detected.')}")
        self.ln(2)
        self.set_font('Arial', '', 9)
        self.set_text_color(*self.text_light)
        self.multi_cell(0, 5, f"Detailed Interpretation: {data.get('report', {}).get('interpretation', '')} {data.get('diagnosis_details', '')}")

        # 4. ENGINEERING MITIGATION
        self.create_section_header("4. Engineering Mitigation Directive")
        correction = data.get('correction', {})
        if correction.get('action') != "NONE":
            self.set_font('Arial', 'B', 10)
            self.set_text_color(180, 0, 0)
            self.cell(0, 8, f"REQUIRED ACTION: {correction['action']}", 0, 1)
            self.set_text_color(*self.text_dark)
            self.set_font('Arial', '', 10)
            self.cell(0, 8, f"- Counter-Ballast Mass: {correction['mass']:.1f} grams", 0, 1)
            self.cell(0, 8, f"- Placement Coordinate: {correction['location']:.1f} cm Axial from Root", 0, 1)
        else:
            self.set_font('Arial', 'B', 10)
            self.set_text_color(22, 163, 74)
            self.cell(0, 10, "CERTIFICATION: STRUCTURAL DNA VALIDATED. NO MITIGATION REQUIRED.", 0, 1)

        # Final Save
        self.output(output_path)
        return output_path

def generate_pdf_report(data, filename="report.pdf"):
    """Helper function for app.py"""
    logo = os.path.join(os.path.dirname(os.path.dirname(__file__)), "static", "logo.png")
    reporter = BladeReportGenerator(logo_path=logo)
    return reporter.generate(data, filename)